# update.yml 
---
 - name: Update all deb based servers
   become: yes
   hosts: all

   tasks:

    - name: Update all Packages
      apt:
        update_cache: yes 

    - name: Upgrade all Packages
      register: updatesys
      apt:
        name: "*"
        state: latest


    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{updatesys.stdout_lines|last}}"